import {defineArrayMember, defineField, defineType} from 'sanity'
import {CogIcon} from '@sanity/icons/Cog'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Réglages du site',
  type: 'document',
  icon: CogIcon,
  groups: [
    {name: 'availability', title: 'Disponibilité', default: true},
    {name: 'contact', title: 'Contact'},
    {name: 'stats', title: 'Chiffres & stack'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'availabilityHeadline',
      title: 'Disponibilité (en-tête)',
      type: 'internationalizedArrayString',
      group: 'availability',
      description: 'Pastille du menu, par exemple « Disponible pour de nouveaux projets ».',
    }),
    defineField({
      name: 'availabilityShort',
      title: 'Disponibilité (courte)',
      type: 'internationalizedArrayString',
      group: 'availability',
      description: 'Pastille de la section contact de l’accueil, par exemple « Disponible ».',
    }),
    defineField({
      name: 'availabilityDetail',
      title: 'Disponibilité (détail)',
      type: 'internationalizedArrayString',
      group: 'availability',
      description: 'Page À propos, par exemple « Disponible · Immédiatement ».',
    }),
    defineField({
      name: 'status',
      title: 'Statut (page Contact)',
      type: 'internationalizedArrayString',
      group: 'availability',
      description: 'Par exemple « Disponible · Ouvert à toutes opportunités ».',
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.required().email(),
    }),
    defineField({
      name: 'socialLinks',
      title: 'Réseaux',
      type: 'array',
      group: 'contact',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'socialLink',
          fields: [
            defineField({name: 'label', title: 'Nom', type: 'string', validation: (rule) => rule.required()}),
            defineField({
              name: 'url',
              title: 'Lien',
              type: 'url',
              validation: (rule) => rule.required().uri({scheme: ['https', 'http', 'mailto']}),
            }),
          ],
          preview: {select: {title: 'label', subtitle: 'url'}},
        }),
      ],
    }),
    defineField({
      name: 'location',
      title: 'Localisation',
      type: 'internationalizedArrayString',
      group: 'contact',
      description: 'Par exemple « Abidjan, Côte d’Ivoire (GMT+0) ».',
    }),
    defineField({
      name: 'languages',
      title: 'Langues parlées',
      type: 'internationalizedArrayString',
      group: 'contact',
    }),
    defineField({
      name: 'cv',
      title: 'CV (PDF)',
      type: 'file',
      group: 'contact',
      options: {accept: 'application/pdf'},
    }),
    defineField({
      name: 'yearsOfExperience',
      title: 'Années d’expérience',
      type: 'string',
      group: 'stats',
      description: 'Par exemple « 2+ ».',
    }),
    defineField({
      name: 'projectsCount',
      title: 'Projets en production',
      type: 'string',
      group: 'stats',
      description: 'Laisser vide pour compter automatiquement les projets publiés.',
    }),
    defineField({
      name: 'sectorsCount',
      title: 'Nombre de secteurs',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'sectorsList',
      title: 'Liste des secteurs',
      type: 'internationalizedArrayString',
      group: 'stats',
      description: 'Par exemple « IA, institutionnel, e-commerce, agence ».',
    }),
    defineField({
      name: 'technologiesCount',
      title: 'Technologies maîtrisées',
      type: 'string',
      group: 'stats',
      description: 'Par exemple « 13+ ».',
    }),
    defineField({
      name: 'homeStack',
      title: 'Stack de l’accueil',
      type: 'array',
      group: 'stats',
      description: 'Bandeau « Ma stack » de la page d’accueil.',
      of: [defineArrayMember({type: 'string'})],
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'seoTitle',
      title: 'Titre du site',
      type: 'internationalizedArrayString',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription',
      title: 'Description',
      type: 'internationalizedArrayText',
      group: 'seo',
    }),
    defineField({
      name: 'ogImage',
      title: 'Image de partage (1200 × 630)',
      type: 'image',
      group: 'seo',
      options: {hotspot: true},
    }),
  ],
  preview: {
    prepare: () => ({title: 'Réglages du site'}),
  },
})
