/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  shortName?: string;
  category?: InternationalizedArrayString;
  year?: string;
  subtitle?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  role?: InternationalizedArrayString;
  stack?: Array<string>;
  url?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  orderRank?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayString
  | InternationalizedArrayText
  | Slug
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(orderRank asc, year desc) {    _id,    name,    "slug": slug.current,    shortName,    year,    url,    stack,    "tag": { "fr": category[language == "fr"][0].value, "en": category[language == "en"][0].value },    "sub": { "fr": subtitle[language == "fr"][0].value, "en": subtitle[language == "en"][0].value },    "description": { "fr": description[language == "fr"][0].value, "en": description[language == "en"][0].value },    "role": { "fr": role[language == "fr"][0].value, "en": role[language == "en"][0].value },    coverImage { asset, alt, hotspot, crop }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  shortName: string | null;
  year: string | null;
  url: string | null;
  stack: Array<string> | null;
  tag: {
    fr: string | null;
    en: string | null;
  };
  sub: {
    fr: string | null;
    en: string | null;
  };
  description: {
    fr: string | null;
    en: string | null;
  };
  role: {
    fr: string | null;
    en: string | null;
  };
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "project" && defined(slug.current)] | order(orderRank asc, year desc) {\n    _id,\n    name,\n    "slug": slug.current,\n    shortName,\n    year,\n    url,\n    stack,\n    "tag": { "fr": category[language == "fr"][0].value, "en": category[language == "en"][0].value },\n    "sub": { "fr": subtitle[language == "fr"][0].value, "en": subtitle[language == "en"][0].value },\n    "description": { "fr": description[language == "fr"][0].value, "en": description[language == "en"][0].value },\n    "role": { "fr": role[language == "fr"][0].value, "en": role[language == "en"][0].value },\n    coverImage { asset, alt, hotspot, crop }\n  }\n': PROJECTS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
